Bump Nix
Change-Id: I5cf8d367a3708c121c87ba33bff36f9e6e710c00

diff --git a/gnu/packages/patches/nix-dont-build-html-doc.diff b/gnu/packages/patches/nix-dont-build-html-doc.diff
--- a/gnu/packages/patches/nix-dont-build-html-doc.diff
+++ b/gnu/packages/patches/nix-dont-build-html-doc.diff
@@ -5,30 +5,45 @@ Author: Zhu Zihao <all_but_last@163.com>
 
 --- a/doc/manual/local.mk
 +++ b/doc/manual/local.mk
-@@ -138,11 +138,6 @@
- 	$(trace-gen) $(dummy-env) NIX_PATH=nix/corepkgs=corepkgs $(bindir)/nix __dump-builtins > $@.tmp
- 	@mv $@.tmp $@
+@@ -166,21 +166,6 @@
+ 	  true > $@; \
+ 	fi
  
 -# Generate the HTML manual.
 -.PHONY: manual-html
 -manual-html: $(docdir)/manual/index.html
+-
+-# Open the built HTML manual in the default browser.
+-manual-html-open: $(docdir)/manual/index.html
+-	@echo "  OPEN  " $<; \
+-	  xdg-open $< \
+-		  || open $< \
+-			|| { \
+-		echo "Could not open the manual in a browser. Please open '$<'" >&2; \
+-		false; \
+-		}
 -install: $(docdir)/manual/index.html
 -
  # Generate 'nix' manpages.
- install: $(mandir)/man1/nix3-manpages
- man: doc/manual/generated/man1/nix3-manpages
-@@ -167,23 +162,4 @@
+ .PHONY: manpages
+ manpages: $(mandir)/man1/nix3-manpages
+@@ -206,26 +191,3 @@
+ 		rm $$tmpFile; \
  	done
  	@touch $@
- 
--$(docdir)/manual/index.html: $(MANUAL_SRCS) $(d)/book.toml $(d)/anchors.jq $(d)/custom.css $(d)/src/SUMMARY.md $(d)/src/command-ref/new-cli $(d)/src/contributing/experimental-feature-descriptions.md $(d)/src/command-ref/conf-file.md $(d)/src/language/builtins.md
+-
+-# the `! -name 'documentation.md'` filter excludes the one place where
+-# `@docroot@` is to be preserved for documenting the mechanism
+-# FIXME: maybe contributing guides should live right next to the code
+-# instead of in the manual
+-$(docdir)/manual/index.html: $(MANUAL_SRCS) $(d)/book.toml $(d)/anchors.jq $(d)/custom.css $(d)/src/SUMMARY.md $(d)/src/store/types $(d)/src/command-ref/new-cli $(d)/src/development/experimental-feature-descriptions.md $(d)/src/command-ref/conf-file.md $(d)/src/language/builtins.md $(d)/src/release-notes/rl-next.md $(d)/src/figures $(d)/src/favicon.png $(d)/src/favicon.svg
 -	$(trace-gen) \
 -		tmp="$$(mktemp -d)"; \
 -		cp -r doc/manual "$$tmp"; \
 -		find "$$tmp" -name '*.md' | while read -r file; do \
 -			$(call process-includes,$$file,$$file); \
 -		done; \
--		find "$$tmp" -name '*.md' | while read -r file; do \
+-		find "$$tmp" -name '*.md' ! -name 'documentation.md' | while read -r file; do \
 -			docroot="$$(realpath --relative-to="$$(dirname "$$file")" $$tmp/manual/src)"; \
 -			sed -i "s,@docroot@,$$docroot,g" "$$file"; \
 -		done; \
@@ -39,5 +54,3 @@ Author: Zhu Zihao <all_but_last@163.com>
 -	@rm -rf $(DESTDIR)$(docdir)/manual
 -	@mv $(DESTDIR)$(docdir)/manual.tmp/html $(DESTDIR)$(docdir)/manual
 -	@rm -rf $(DESTDIR)$(docdir)/manual.tmp
--
- endif
